<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="45687" started-at="2020-07-14T17:05:19 IST" finished-at="2020-07-14T17:06:05 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="45687" started-at="2020-07-14T17:05:19 IST" finished-at="2020-07-14T17:06:05 IST">
      <class name="com.guru.test.UserInterfaceSortingTest">
        <test-method status="PASS" signature="initMethod()[pri:0, instance:com.guru.test.UserInterfaceSortingTest@4461c7e3]" name="initMethod" is-config="true" duration-ms="23604" started-at="2020-07-14T17:05:19 IST" finished-at="2020-07-14T17:05:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initMethod -->
        <test-method status="FAIL" signature="to_Verify_Discount_Coupon_Works_Correctly()[pri:0, instance:com.guru.test.UserInterfaceSortingTest@4461c7e3]" name="to_Verify_Discount_Coupon_Works_Correctly" duration-ms="21977" started-at="2020-07-14T17:05:43 IST" finished-at="2020-07-14T17:06:05 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Coupon code cannot Applied correctly expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Coupon code cannot Applied correctly expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:968)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.guru.test.UserInterfaceSortingTest.to_Verify_Discount_Coupon_Works_Correctly(UserInterfaceSortingTest.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- to_Verify_Discount_Coupon_Works_Correctly -->
      </class> <!-- com.guru.test.UserInterfaceSortingTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
